[package]
name = "hk"
version = "0.1.0"
authors = ["Aryailia <Aryailia@users.noreply.github.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
unicode-width = "0.1.8"
