name: Publish to gh-pages branch (root for hosted site)
on:
  workflow_dispatch: # So I can manually run it
  #repository_dispatch:
  #  types: ["Update from a-bas-le-ciel-data"]
  push:
    branches: [main, update]

  #Dont run this on cron because, github puts this to sleep
  #schedule:
  #  - cron: "0 14 * * 2"  # Once a week on Tuesday at 14:00 UTC

permissions:
  pages: write
  id-token: write # Needed for gh-pages

env:
  CARGO_TERM_COLOR: always
  publish: ${{ github.workspace }}/publish
  #publish: ${{ github.workspace }}/chordscript-wasm/publish

jobs:
  make_site:
    runs-on: ubuntu-latest
    steps:
      - name: Clone
        env:
          repo: https://github.com/yueleshia/chordscript
          dir:  ${{ github.workspace }}/repo
        run: |-
          printf %s\\n "" "=== Fetch yueleshia/chordscript ===" >&2
          git init "${dir}" || exit "$?"
          git -C "${dir}" remote add origin "${repo}" || exit "$?"
          git -C "${dir}" fetch --depth 1 origin refs/heads/main || exit "$?"
          git -C "${dir}" switch --detach FETCH_HEAD || exit "$?"

      - name: Download wasm-pack
        run:  curl https://rustwasm.github.io/wasm-pack/installer/init.sh -sSf | bash

      - name: Build with rust wasm-pack
        env:
          dir: "${{ github.workspace }}/repo"
        run:  |
          "${dir}/chordscript-wasm/make.sh" "${publish}"

      - name: Upload static files as artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: "${{ env.publish }}"

      - name: Deploy to GitHub Pages
        uses: actions/deploy-pages@v4
